banool/team_heist_tactics

- src/lib.rs
- src/load_json.rs
- src/load_map.rs
- src/types.rs
Abandoned https://github.com/banool/team_heist_tactics/pull/3 in favor of this, since I messed up my branches.
> Add load_map.rs and Serializable* types to serialize tiles to JSON

- src/game.rs
- src/types.rs
> Character collision makes moves Invalid

- src/game.rs
- src/manager.rs
And rustfmt, etc.
Some random server log cleanup, too.
Refactored some of the bulk of `process_move` into helpers:
* `move_blocked_by_wall`
* `position_is_occupied`
Yeah, idk. these could be named more nicely to imply that they are Validity checks, but idk
> Fix wall collision AND heister collision. Add test for heister collision

- static/images/001a.jpg
- static/images/003.jpg
- static/images/004.jpg
> updates orange and yellow on tiles

- static/images/008.jpg
- static/images/009.jpg
> adds 009 and fixes 008 naming

- src/game.rs
- src/types.rs
Added also some form of unit testing... fix is one line -_-
> Fix copypasta mistake in checking whether heister is at matching door

- src/game.rs
Tests broke, I fixed them and fixed the diff...
Things that are bad:
panic! - i could use errors and stuff, but I don't know how and this works /shrug
...
that's prety much it. i think it's pretty alright in general.
it's awesome to have characters move to new tiles!
close #26 #29
> Change {Color}Door wall to be Clear after a tile is placed though it

- static/images/002.jpg
- static/images/003.jpg
- static/images/004.jpg
- static/images/005.jpg
- static/images/006.jpg
- static/images/009.jpg
> rotates all tiles to face up

- src/game.rs
Turned out I should have used the exclusive range anyways! 
Lots of unit test refactoring, IDK if it's worth it, but I think it will make writing more tests easier.
close #29
> Fix tile re-entry + Add unit tests for crossing into new tile and moving back into old tile

- src/game.rs
https://media1.giphy.com/media/vka8RVWJLaLy8/giphy.gif
has to do with closing #42
> Initial escalator moves

- ui/jest.config.js
- ui/package.json
- ui/src/join_game/helpers.spec.ts
- ui/src/join_game/helpers.ts
- ui/tsconfig.json
Weird. Maybe I need to rebase // update again.
ANyways, this is unit test start for using yarn test + jest.
> Initial unit tests for UI/TypeScript

- ui/src/join_game/helpers.spec.ts
These are correct values from a version of mapPositiontoCanvasPosition I was testing with, but I've commented these tests out with `-- BROKEN` so that they don't break our build. 
When working on code for this function, please uncomment those tests and use them. If they break... for incorrect reasons, let me know.
> Updated unit test values commented bc broken currently but theyre correct

- .github/workflows/backend_style.yml
- .github/workflows/backend_test.yml
- .github/workflows/build.yml
- .github/workflows/frontend_style.yml
- .github/workflows/frontend_test.yml
- other/pre-commit
- ui/generate_types.sh
> Fix GitHub actions

- ui/src/join_game/GameWindowComponent.tsx
- ui/src/join_game/helpers.spec.ts
- ui/src/join_game/helpers.ts
on a new branch so me (fatema) can access it from me (fatema) computer
> try one of fatema's formula for canvasPos

- src/game.rs
Cleanup as prep for uhhh making "Doors be opened automatically" when a new tile has a door that lines up with an existing door.
This PR will resolve the issue we made specifically about these panics, which actually can cause server crashes, in that exact case (you can draw a tile over one that already exists, currently), and then I plan to fix the door-opening-on-tile-placement next.
> Change open_door() panics to be Result/Err/Ok

- ui/src/join_game/helpers.ts
A BITCH IS TIRED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I _do not_ know if @kemcbride's tests pass and I _do not_ care
> GETS TILE POSITIONING CORRECT FINALLY HOLY

- src/game.rs
- src/types.rs
Enjoy!
It looks pretty good and includes a bit of tidying.
And with some TODOs for further cleanup... moving functions from Game to a proper type for them.
Eg. like how I added opposite() for MoveDirection, and some functions for MapPosition just on the struct itself.
Hannnndy.
> Add logic to open adjacent doors for newly-drawn tiles

- src/game.rs
- src/types.rs
and into an appropriate type (MapPosition)
> Some cleanup, moving helper functions out of game.rs

- src/game.rs
- src/types.rs
fixes #92 
I should add unit tests.
They're relatively easy to write, and would ensure this doesn't get broken later.
"tEsTeD oN My mAcHinE"
> Symmetric doors pls

- src/game.rs
- src/types.rs
just some cleanup. see that checks, pass, beep boop
close #114
> Refactor/cleanup for move_in_direction - become method on MapPosition

- src/lib.rs
- src/main.rs
- src/manager.rs
- src/periodic.rs
Had to go through some fixing for this one, but it seems to be working. Uh, honestly, the best way to test it is by running it. I'll update with some test output (setting INTERVAL & DURATION to small numbers so you can see the reaper run as expected)
fixes #71
> Modified time on games plus reaper maybe

- ui/src/join_game/api.ts
This is working pretty simply & reliably for me having done like 1 full minute of UI testing.
I'm tempted to just merge it, but feedback is appreciated.
I tried to refactor all those validation checks into a separate function, but then there were tons of vscode warnings that said that many types being used "could be undefined", so I instead just left the checks in place.
There ought to be a nice way to get it to be both reusable and not have those warnings.
Either way - this is pretty straight forward. At first I thought it was broken, but turns out I didn't know how to properly access javascript/typescript maps. Then it just worked easy peasy!
> Escalator keyboard ui

- ui/src/join_game/api.ts
How does this work?
The server keeps a stable list of all the teleports revealed per color.
The server sends the list of teleports per color for each heister if it's on any teleport square.
The UI looks at that list, finds the current position in the list it's at (the list is ordered by tile discovery, for those who are curious), adds 1 mod length to get the next teleport, and attempts to move the heister there.
Seems legit to me.
close #33
> Add ability to teleport using keyboard

- src/periodic.rs
close #126 
straightforward cleanup
> Cleanup unused import in periodic.rs

- src/game.rs
- src/main.rs
Pretty small, gets it done.
fix #141
> Move hard teleports into their own GameOption, and have it be off by default

- templates/index.html
- ui/src/join_game/JoinGameForm.tsx
- ui/src/join_game/LobbyForm.tsx
fix #136 
Hoo wee. 
Thanks stackoverflow. I can share the two links...
https://stackoverflow.com/questions/33211672/how-to-submit-a-form-using-enter-key-in-react-js
https://stackoverflow.com/questions/42324423/autofocus-an-input-element-in-react-js
This does exactly what I wanted. I'm going to merge it without review.
> Autofocus & auto submit w/enter on all intro forms

- src/game.rs
- src/game_state.rs
- src/lib.rs
- src/serializer.rs
- src/types.rs
Cleanup for both types.rs & game.rs
fixes #125
> [WIP] Moving defn & impl for GameState into its own file. 

- run.sh
- templates/index.html
- ui/src/components/main.css
- ui/src/components/styles.ts
- ui/src/join_game/JoinGameForm.tsx
- ui/src/join_game/MainPage.tsx
- ui/templates/index.html
Still need to make lots of changes ofc
> makes it pink and blue (partially)

- src/game.rs
- src/game_state.rs
- src/types.rs
fix #151 
Technically should come with change to allow game to stay on screen in DEFEAT case.
> [WIP] Timer flips when you step on a timer, also DEFEAT if timer runs out

- src/game.rs
- src/game_state.rs
- src/types.rs
> Escape happens automatically, victory status is set

- ui/src/join_game/GameWindowComponent.tsx
Implements https://github.com/banool/team_heist_tactics/issues/59.
> Add ability to zoom with scroll wheel

- src/game_state.rs
- src/types.rs
Getting rid of old TODOs that I had in the code.
This one was pretty trivial but do I love how I did it? Flat functions? Not really.
I would have had to add a full on support for WallType and conversions to/from the proto type, though, and I didn't feel like doing that. /shrug
> Wall->Color helper

- src/game.rs
- src/game_state.rs
- src/types.rs
A little bit of safety and checking, and bim bam boom. Looking pretty good.
The primary concern I have, having fixed a couple of bugs in it as part of this PR, is this:
* what if walls/doors are not symmetrical?
I check pairwise going in one direction, not both. Either way, it's a problem for later. Yay for click'n'drag users.
close #97
> Allow multi-space click'n'drag moves
